
"""
report_generator.py
Generate a PDF optimization report for EcoLoop using reportlab.
"""

from pathlib import Path
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet

OUTPUT_DIR = Path("outputs")
OUTPUT_DIR.mkdir(exist_ok=True)


def generate_report(metrics, decision, summary=None,
                    filename="outputs/EcoLoop_Report.pdf"):
    """
    Generate a PDF report and return its path.
    """
    styles = getSampleStyleSheet()
    doc = SimpleDocTemplate(filename)

    story = []

    story.append(Paragraph("<b>EcoLoop Building Optimization Report</b>",
                           styles["Title"]))
    story.append(Paragraph(
        "Generated by the EcoLoop AI Building Management System.",
        styles["BodyText"]))
    story.append(Spacer(1, 12))

    story.append(Paragraph("<b>Current Building Metrics</b>",
                           styles["Heading2"]))

    metrics_table = Table([
        ["Metric", "Value"],
        ["Timestamp", str(metrics.timestamp)],
        ["Energy (kWh)", f"{metrics.energy_kwh:.2f}"],
        ["Demand (kW)", f"{metrics.demand_kw:.2f}"],
        ["Indoor Temp", f"{metrics.indoor_temperature} °C"],
        ["Outdoor Temp", f"{metrics.outdoor_temperature} °C"],
        ["Humidity", f"{metrics.humidity}%"],
        ["Occupancy", str(metrics.occupancy)],
    ])

    metrics_table.setStyle(TableStyle([
        ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
        ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0,0), (-1,0), 8),
    ]))
    story.append(metrics_table)
    story.append(Spacer(1, 16))

    story.append(Paragraph("<b>AI Optimization Decision</b>",
                           styles["Heading2"]))

    decision_table = Table([
        ["Setting", "Value"],
        ["Cooling Setpoint", f"{decision.cooling_setpoint} °C"],
        ["Heating Setpoint", f"{decision.heating_setpoint} °C"],
        ["Lighting", f"{decision.lighting_level}%"],
        ["Fan Speed", f"{decision.fan_speed}%"],
    ])

    decision_table.setStyle(TableStyle([
        ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
        ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
    ]))
    story.append(decision_table)
    story.append(Spacer(1, 12))

    story.append(Paragraph("<b>Reason</b>", styles["Heading2"]))
    story.append(Paragraph(decision.reason, styles["BodyText"]))
    story.append(Spacer(1, 16))

    if summary:
        story.append(Paragraph("<b>Optimization Summary</b>",
                               styles["Heading2"]))
        summary_rows = [["Statistic", "Value"]]
        for k, v in summary.items():
            summary_rows.append([str(k).replace("_", " ").title(), str(v)])
        summary_table = Table(summary_rows)
        summary_table.setStyle(TableStyle([
            ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
            ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
            ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ]))
        story.append(summary_table)

    story.append(Spacer(1, 20))
    story.append(Paragraph(
        "EcoLoop • Honeywell Hackathon • AI Building Optimization",
        styles["Italic"]))

    doc.build(story)
    return filename
